/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Wolf.gltf --transform 
Files: public/models/Wolf.gltf [3.18MB] > C:\Users\tibog\Documents\VSCODE\wawa-game-template\Wolf-transformed.glb [542KB] (83%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Wolf-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
        </group>
        <group name="Wolf">
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Main} skeleton={nodes.Cube.skeleton} />
          <skinnedMesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Nose} skeleton={nodes.Cube_1.skeleton} />
          <skinnedMesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.Main_Light} skeleton={nodes.Cube_2.skeleton} />
          <skinnedMesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.Eyes_Black} skeleton={nodes.Cube_3.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Wolf-transformed.glb')
